/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueaderotulcan.vista;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import parqueaderotulcan.controlador.GestorConductor;
import parqueaderotulcan.modelo.Conductor;

/**
 *
 * @author Felipe Vidal y Aldair Zemanate
 */
public class VistaVincularConductorAutomovil extends javax.swing.JFrame {
    VistaConsultaConductor vcc;
    boolean estadoConductor;
    /**
     * Creates new form VistaVincularConductorAutomovil
     */
    public VistaVincularConductorAutomovil(VistaConsultaConductor vcc) {
        this.vcc=vcc;
        initComponents();
        inicializarTabla();
        vcc.setVisible(false);
    }
    private void inicializarTabla(){
        tblDatosConductor.setModel(new javax.swing.table.DefaultTableModel(new Object [] [] {},new String[]{"Nombre","Apellido","Cedula","Código","Fecha Nacimiento","Rol"}));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPlaca = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        txtId = new java.awt.TextField();
        btnVincular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatosConductor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Universidad del cauca ");
        jPanel2.add(jLabel3, new java.awt.GridBagConstraints());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Vincular conductor-vehiculo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jLabel4, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jLabel8.setText("2020 | División de Tecnologías de la Información y las Comunicaciones Universidad del Cauca");
        jPanel4.add(jLabel8);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Placa del automovil:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtPlaca.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(txtPlaca, new java.awt.GridBagConstraints());

        jLabel2.setText("Numero de documento del conductor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel1.add(jLabel2, gridBagConstraints);

        txtId.setPreferredSize(new java.awt.Dimension(200, 20));
        txtId.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txtIdTextValueChanged(evt);
            }
        });
        jPanel1.add(txtId, new java.awt.GridBagConstraints());

        btnVincular.setText("Vincular");
        btnVincular.setEnabled(false);
        btnVincular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVincularActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel1.add(btnVincular, gridBagConstraints);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 100));

        tblDatosConductor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDatosConductor.setPreferredSize(new java.awt.Dimension(700, 16));
        jScrollPane1.setViewportView(tblDatosConductor);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVincularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVincularActionPerformed
        GestorConductor gc = new GestorConductor();
        if(isNumeric(txtId.getText())==true){
            if(txtPlaca.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Ingrese una placa");
            }else{
                gc.vincularConductorVehiculo(txtPlaca.getText(),txtId.getText());
            }
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese un valor entero en el campo 'Numero de documento del conductor'");

        }
    }//GEN-LAST:event_btnVincularActionPerformed

    private void txtIdTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txtIdTextValueChanged
        GestorConductor gc = new GestorConductor();
        Conductor conductor;
        if(isNumeric(txtId.getText())==true){
            conductor = gc.consultarConductorCedula(txtId.getText());
            inicializarTabla();
            if(conductor.getCedula()!=null){
                btnVincular.setEnabled(true);
                DefaultTableModel model = (DefaultTableModel) tblDatosConductor.getModel();
                Object rowData[] = new Object[6];
                rowData[0]=conductor.getNombre();
                rowData[1]=conductor.getApellido();
                rowData[2]=conductor.getCedula();
                rowData[3]=conductor.getCodigo();
                rowData[4]=conductor.getFecha_nacimiento();
                rowData[5]=conductor.getRol();
                model.addRow(rowData);
                 
            }else{
                btnVincular.setEnabled(false);
            }
        }
    }//GEN-LAST:event_txtIdTextValueChanged
private static boolean isNumeric(String cadena){
    try {
        Integer.parseInt(cadena);
        return true;
    } catch (NumberFormatException nfe){
	return false;
    }
}
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        vcc.setVisible(true);
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
                vcc.setVisible(true);

    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVincular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatosConductor;
    private java.awt.TextField txtId;
    private java.awt.TextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
