/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueaderotulcan.vista;

import java.util.Date;
import javax.swing.JOptionPane;
import parqueaderotulcan.controlador.GestorConductor;
import parqueaderotulcan.controlador.GestorMulta;
import parqueaderotulcan.modelo.Conductor;

/**
 *
 * @author Felipe Vidal y Aldair Zemanate
 */
public class VistaRegistrarMulta extends javax.swing.JFrame {
    boolean estadoConductor=false;
    /**
     * Creates new form VistaRegistrarMulta
     */
    public VistaRegistrarMulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCedula = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jDCFechaMulta = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtADescripcion = new java.awt.TextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCBMM = new javax.swing.JComboBox<>();
        jCBHH = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblConductor = new javax.swing.JLabel();
        Registrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Universidad del cauca ");
        jPanel2.add(jLabel4, new java.awt.GridBagConstraints());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Registrar multa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jLabel5, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jLabel10.setText("2020 | División de Tecnologías de la Información y las Comunicaciones Universidad del Cauca");
        jPanel4.add(jLabel10);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Cedula conductor:");
        jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        txtCedula.setPreferredSize(new java.awt.Dimension(60, 20));
        txtCedula.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txtCedulaTextValueChanged(evt);
            }
        });
        jPanel1.add(txtCedula, new java.awt.GridBagConstraints());

        jLabel2.setText("Fecha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jDCFechaMulta, gridBagConstraints);

        jLabel3.setText("Descripción:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        jPanel1.add(txtADescripcion, gridBagConstraints);

        jLabel6.setText("Hora:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setText("hh:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel1.add(jLabel7, gridBagConstraints);

        jLabel8.setText("mm:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        jPanel1.add(jLabel8, gridBagConstraints);

        jCBMM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel1.add(jCBMM, gridBagConstraints);

        jCBHH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", " " }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanel1.add(jCBHH, gridBagConstraints);

        jLabel9.setText("Fotografia");
        jPanel1.add(jLabel9, new java.awt.GridBagConstraints());

        jLabel11.setText("Conductor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jLabel11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel1.add(lblConductor, gridBagConstraints);

        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        jPanel1.add(Registrar, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txtCedulaTextValueChanged
        GestorConductor gc = new GestorConductor();
        Conductor conductor;
        if (isNumeric(txtCedula.getText())==true){
            conductor = gc.consultarConductorCedula(txtCedula.getText());
                if(conductor.getCedula()!=null ){
                lblConductor.setText(conductor.getNombre()+" "+conductor.getApellido());
                estadoConductor=true;
            }
                else{  
                lblConductor.setText("");
                estadoConductor=false;
            }
        }
    }//GEN-LAST:event_txtCedulaTextValueChanged

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        GestorMulta gm;
        gm = new GestorMulta();
        //Se captura la excepción si no se ha ingresado una fecha
        try{
            Date fechaMulta = jDCFechaMulta.getDate();
            long d = fechaMulta.getTime();
            java.sql.Date fecha = new java.sql.Date(d);
            String newFechaMulta = fecha.toString()+" "+jCBHH.getSelectedItem()+":"+jCBMM.getSelectedItem(); 
            //Se comprueba que la cedula del conductor no contenga letras, simbolos o esté vacio
            if(isNumeric(txtCedula.getText())==true){
                if(estadoConductor == true){
                    gm.ingresarMulta(txtCedula.getText(),newFechaMulta , txtADescripcion.getText());
                }else{
                    JOptionPane.showMessageDialog(null,"El conductor no se encuentre registrado en la base de datos");
                }
            }else{
                JOptionPane.showMessageDialog(null,"Ingrese un valor entero en el campo cedula");
            }
        }catch( java.lang.NullPointerException n ){
            JOptionPane.showMessageDialog(null,"Hay campos vacios");
        }
        
    }//GEN-LAST:event_RegistrarActionPerformed
    private static boolean isNumeric(String cadena){
        try {
            Integer.parseInt(cadena);
            return true;
    } catch (NumberFormatException nfe){
	return false;
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registrar;
    private javax.swing.JComboBox<String> jCBHH;
    private javax.swing.JComboBox<String> jCBMM;
    private com.toedter.calendar.JDateChooser jDCFechaMulta;
    public static javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblConductor;
    private java.awt.TextArea txtADescripcion;
    private java.awt.TextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
