/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueaderotulcan.vista;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import parqueaderotulcan.modelo.Mapa;
import parqueaderotulcan.controlador.GestorMapa;
/**
 *
 * @author Felipe Vidal y Aldair Zemanate
 */
public class VistaMapa extends javax.swing.JDialog {

    /**
     * Creates new form Mapas
     */
    public VistaMapa(){
        initComponents();
    }
    public VistaMapa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }
    
    public void actualizar(Mapa [] newMapa){
        
        ArrayList<javax.swing.JTextField> n=new ArrayList<>();
       
        n.add(zEst1);
        n.add(zEst2);
        n.add(zEst3);
        n.add(zEst4);
        n.add(zEst5);
        n.add(zEst6);
        n.add(zAdm1);
        n.add(zAdm2);
        n.add(zAdm3);
        n.add(zAdm4);
        n.add(zAdm5);
        n.add(zAdm6);
        n.add(zVis1);
        n.add(zVis2);
        n.add(zVis3);
        n.add(zVis4);
        n.add(zVis5);
        
        for (int i=0; i<n.size();i++){
            for (Mapa mapa : newMapa){
                if(n.get(i).getName().equals(mapa.getNombrePuesto())){
                IniColor(n.get(i));
            
            }
            
            
//System.out.println(n.get(i).getName());
            }
        }
        this.setVisible(true);
    }
    public void IniColor(javax.swing.JTextField nombre){
        nombre.setBackground(Color.red);
    }
public void Color(javax.swing.JTextField nombre){
    GestorMapa gm = new GestorMapa();
    if(nombre.getBackground()==Color.red){
            int res=JOptionPane.showConfirmDialog(rootPane, "Esta seguro de desocupar bahia");
            switch (res){
                case 0:
                    nombre.setBackground(Color.white);
                    gm.actulizarBahia("Desocupado", nombre.getName());
                    JOptionPane.showMessageDialog(rootPane, "Bahia Desocupada");
                    
                   break; 
                case 1:
                    nombre.setBackground(Color.red);
                    break;
            }                
        }else{
           int res=JOptionPane.showConfirmDialog(rootPane, "Esta seguro de Ocupar bahia");
            switch (res){
                case 0:
                    nombre.setBackground(Color.red);
                    gm.actulizarBahia("Ocupado", nombre.getName());
                    JOptionPane.showMessageDialog(rootPane, "Bahia Ocupada");
                   break; 
                case 1:
                    nombre.setBackground(Color.white);
                    break;
            }
}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        zVis1 = new javax.swing.JTextField();
        zVis2 = new javax.swing.JTextField();
        zVis3 = new javax.swing.JTextField();
        zVis4 = new javax.swing.JTextField();
        zVis5 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        zEst1 = new javax.swing.JTextField();
        zEst2 = new javax.swing.JTextField();
        zEst3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        zEst6 = new javax.swing.JTextField();
        zEst5 = new javax.swing.JTextField();
        zEst4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        zAdm1 = new javax.swing.JTextField();
        zAdm2 = new javax.swing.JTextField();
        zAdm3 = new javax.swing.JTextField();
        zAdm4 = new javax.swing.JTextField();
        zAdm5 = new javax.swing.JTextField();
        zAdm6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 100));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Zona Vistantes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel3, gridBagConstraints);

        zVis1.setEditable(false);
        zVis1.setText("1");
        zVis1.setName("zVis1"); // NOI18N
        zVis1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zVis1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(zVis1, gridBagConstraints);

        zVis2.setEditable(false);
        zVis2.setText("2");
        zVis2.setToolTipText("");
        zVis2.setName("zVis2"); // NOI18N
        zVis2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zVis2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanel1.add(zVis2, gridBagConstraints);

        zVis3.setEditable(false);
        zVis3.setText("3");
        zVis3.setToolTipText("");
        zVis3.setName("zVis3"); // NOI18N
        zVis3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zVis3MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanel1.add(zVis3, gridBagConstraints);

        zVis4.setEditable(false);
        zVis4.setText("4");
        zVis4.setName("zVis4"); // NOI18N
        zVis4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zVis4MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        jPanel1.add(zVis4, gridBagConstraints);

        zVis5.setEditable(false);
        zVis5.setText("5");
        zVis5.setName("zVis5"); // NOI18N
        zVis5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zVis5MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 3, 0, 3);
        jPanel1.add(zVis5, gridBagConstraints);

        jTextField18.setBackground(new java.awt.Color(255, 0, 0));
        jTextField18.setPreferredSize(new java.awt.Dimension(75, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        jPanel1.add(jTextField18, gridBagConstraints);

        jTextField19.setPreferredSize(new java.awt.Dimension(75, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 13);
        jPanel1.add(jTextField19, gridBagConstraints);

        jLabel4.setText("Libre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Ocupado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        panel1.setLayout(new java.awt.GridBagLayout());

        zEst1.setEditable(false);
        zEst1.setText("1");
        zEst1.setName("zEst1"); // NOI18N
        zEst1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zEst1MouseClicked(evt);
            }
        });
        zEst1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zEst1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panel1.add(zEst1, gridBagConstraints);

        zEst2.setEditable(false);
        zEst2.setText("2");
        zEst2.setToolTipText("");
        zEst2.setName("zEst2"); // NOI18N
        zEst2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zEst2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panel1.add(zEst2, gridBagConstraints);

        zEst3.setEditable(false);
        zEst3.setText("3");
        zEst3.setName("zEst3"); // NOI18N
        zEst3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zEst3MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panel1.add(zEst3, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setText("Zona Estudiantes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 0, 0, 0);
        panel1.add(jLabel1, gridBagConstraints);

        zEst6.setEditable(false);
        zEst6.setText("6");
        zEst6.setToolTipText("");
        zEst6.setName("zEst6"); // NOI18N
        zEst6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zEst6MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panel1.add(zEst6, gridBagConstraints);

        zEst5.setEditable(false);
        zEst5.setText("5");
        zEst5.setName("zEst5"); // NOI18N
        zEst5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zEst5MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panel1.add(zEst5, gridBagConstraints);

        zEst4.setEditable(false);
        zEst4.setText("4");
        zEst4.setName("zEst4"); // NOI18N
        zEst4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zEst4MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panel1.add(zEst4, gridBagConstraints);

        getContentPane().add(panel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Zona Administrativos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel2.add(jLabel2, gridBagConstraints);

        zAdm1.setEditable(false);
        zAdm1.setText("1");
        zAdm1.setName("zAdm1"); // NOI18N
        zAdm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zAdm1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel2.add(zAdm1, gridBagConstraints);

        zAdm2.setEditable(false);
        zAdm2.setText("2");
        zAdm2.setName("zAdm2"); // NOI18N
        zAdm2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zAdm2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel2.add(zAdm2, gridBagConstraints);

        zAdm3.setEditable(false);
        zAdm3.setText("3");
        zAdm3.setName("zAdm3"); // NOI18N
        zAdm3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zAdm3MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel2.add(zAdm3, gridBagConstraints);

        zAdm4.setEditable(false);
        zAdm4.setText("4");
        zAdm4.setName("zAdm4"); // NOI18N
        zAdm4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zAdm4MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel2.add(zAdm4, gridBagConstraints);

        zAdm5.setEditable(false);
        zAdm5.setText("5");
        zAdm5.setName("zAdm5"); // NOI18N
        zAdm5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zAdm5MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel2.add(zAdm5, gridBagConstraints);

        zAdm6.setEditable(false);
        zAdm6.setText("6");
        zAdm6.setName("zAdm6"); // NOI18N
        zAdm6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zAdm6MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 1, 0, 0);
        jPanel2.add(zAdm6, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zAdm1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zAdm1MouseClicked
      
        this.Color(zAdm1);
    }//GEN-LAST:event_zAdm1MouseClicked

    private void zAdm2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zAdm2MouseClicked
        this.Color(zAdm2);
    }//GEN-LAST:event_zAdm2MouseClicked

    private void zAdm3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zAdm3MouseClicked
        this.Color(zAdm3);
    }//GEN-LAST:event_zAdm3MouseClicked

    private void zAdm4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zAdm4MouseClicked
        this.Color(zAdm4);
    }//GEN-LAST:event_zAdm4MouseClicked

    private void zAdm5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zAdm5MouseClicked
        this.Color(zAdm5);
    }//GEN-LAST:event_zAdm5MouseClicked

    private void zAdm6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zAdm6MouseClicked
        this.Color(zAdm6);
    }//GEN-LAST:event_zAdm6MouseClicked

    private void zEst1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zEst1MouseClicked
        this.Color(zEst1);

    }//GEN-LAST:event_zEst1MouseClicked

    private void zEst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zEst1ActionPerformed
        System.out.println(evt.getActionCommand());
    }//GEN-LAST:event_zEst1ActionPerformed

    private void zEst2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zEst2MouseClicked
        this.Color(zEst2);
    }//GEN-LAST:event_zEst2MouseClicked

    private void zEst3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zEst3MouseClicked
        this.Color(zEst3);
    }//GEN-LAST:event_zEst3MouseClicked

    private void zEst6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zEst6MouseClicked
        this.Color(zEst6);
    }//GEN-LAST:event_zEst6MouseClicked

    private void zEst5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zEst5MouseClicked
        this.Color(zEst5);
    }//GEN-LAST:event_zEst5MouseClicked

    private void zEst4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zEst4MouseClicked
        this.Color(zEst4);
    }//GEN-LAST:event_zEst4MouseClicked

    private void zVis1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zVis1MouseClicked
        this.Color(zVis1);
    }//GEN-LAST:event_zVis1MouseClicked

    private void zVis2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zVis2MouseClicked
        this.Color(zVis2);
    }//GEN-LAST:event_zVis2MouseClicked

    private void zVis3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zVis3MouseClicked
        this.Color(zVis3);
    }//GEN-LAST:event_zVis3MouseClicked

    private void zVis4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zVis4MouseClicked
        this.Color(zVis4);
    }//GEN-LAST:event_zVis4MouseClicked

    private void zVis5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zVis5MouseClicked
        this.Color(zVis5);
    }//GEN-LAST:event_zVis5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private java.awt.Panel panel1;
    private javax.swing.JTextField zAdm1;
    private javax.swing.JTextField zAdm2;
    private javax.swing.JTextField zAdm3;
    private javax.swing.JTextField zAdm4;
    private javax.swing.JTextField zAdm5;
    private javax.swing.JTextField zAdm6;
    private javax.swing.JTextField zEst1;
    private javax.swing.JTextField zEst2;
    private javax.swing.JTextField zEst3;
    private javax.swing.JTextField zEst4;
    private javax.swing.JTextField zEst5;
    private javax.swing.JTextField zEst6;
    private javax.swing.JTextField zVis1;
    private javax.swing.JTextField zVis2;
    private javax.swing.JTextField zVis3;
    private javax.swing.JTextField zVis4;
    private javax.swing.JTextField zVis5;
    // End of variables declaration//GEN-END:variables
}
