/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueaderotulcan.vista;

/**
 *
 * @author Felipe Vidal y Aldair Zemanate
 */
public class VistaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form VistaAdministrador
     */
    public VistaAdministrador() {
        initComponents();
        
    }
    public void infoAdministrador(String nombre,String apellido,String genero, String fechaNacimiento, String id){
        lblNombre.setText(nombre);
        lblApellido.setText(apellido);
        lblGenero.setText(genero);
        lblFechaNacimiento.setText(fechaNacimiento);
        lblId.setText(id);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        label5 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbNam = new javax.swing.JLabel();
        lblApeliidos = new javax.swing.JLabel();
        lblGen = new javax.swing.JLabel();
        lblFN = new javax.swing.JLabel();
        lblFN1 = new javax.swing.JLabel();
        lblNombre = new java.awt.Label();
        lblApellido = new java.awt.Label();
        lblGenero = new java.awt.Label();
        lblFechaNacimiento = new java.awt.Label();
        lblId = new java.awt.Label();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Opciones = new javax.swing.JMenu();
        jMOpIngresarVigilante = new javax.swing.JMenuItem();
        jMOpCerrarSesion = new javax.swing.JMenuItem();

        label5.setText("label5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Universidad del cauca ");
        jPanel2.add(jLabel4, new java.awt.GridBagConstraints());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Administrador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jLabel5, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jLabel8.setText("2020 | División de Tecnologías de la Información y las Comunicaciones Universidad del Cauca");
        jPanel4.add(jLabel8);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lbNam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNam.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel1.add(lbNam, gridBagConstraints);

        lblApeliidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblApeliidos.setText("Apellidos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel1.add(lblApeliidos, gridBagConstraints);

        lblGen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGen.setText("Genero:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        jPanel1.add(lblGen, gridBagConstraints);

        lblFN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFN.setText("Identificación:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel1.add(lblFN, gridBagConstraints);

        lblFN1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFN1.setText("Fecha Nacimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel1.add(lblFN1, gridBagConstraints);

        lblNombre.setText("label1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel1.add(lblNombre, gridBagConstraints);

        lblApellido.setText("label2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel1.add(lblApellido, gridBagConstraints);

        lblGenero.setText("label3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        jPanel1.add(lblGenero, gridBagConstraints);

        lblFechaNacimiento.setText("label4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        jPanel1.add(lblFechaNacimiento, gridBagConstraints);

        lblId.setText("label6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanel1.add(lblId, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Usuario:");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jLabel6, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        Opciones.setText("Opciones");

        jMOpIngresarVigilante.setText("Ingresar vigilante");
        jMOpIngresarVigilante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMOpIngresarVigilanteActionPerformed(evt);
            }
        });
        Opciones.add(jMOpIngresarVigilante);

        jMOpCerrarSesion.setText("Cerrar Sesión");
        jMOpCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMOpCerrarSesionActionPerformed(evt);
            }
        });
        Opciones.add(jMOpCerrarSesion);

        jMenuBar1.add(Opciones);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMOpCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMOpCerrarSesionActionPerformed
        this.setVisible(false);
        VistaLogin vl = new VistaLogin();
        vl.setVisible(true);
    }//GEN-LAST:event_jMOpCerrarSesionActionPerformed

    private void jMOpIngresarVigilanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMOpIngresarVigilanteActionPerformed
        VistaRegistrarVigilante vrv = new VistaRegistrarVigilante(this);
        vrv.setVisible(true);
    }//GEN-LAST:event_jMOpIngresarVigilanteActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Opciones;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMOpCerrarSesion;
    private javax.swing.JMenuItem jMOpIngresarVigilante;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private java.awt.Label label5;
    private javax.swing.JLabel lbNam;
    private javax.swing.JLabel lblApeliidos;
    private java.awt.Label lblApellido;
    private javax.swing.JLabel lblFN;
    private javax.swing.JLabel lblFN1;
    private java.awt.Label lblFechaNacimiento;
    private javax.swing.JLabel lblGen;
    private java.awt.Label lblGenero;
    private java.awt.Label lblId;
    private java.awt.Label lblNombre;
    // End of variables declaration//GEN-END:variables
}
