/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueaderotulcan.vista;

import parqueaderotulcan.controlador.GestorMapa;

/**
 *
 * @author Felipe Vidal y Aldair Zemanate
 */
public class VistaVigilante extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public VistaVigilante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblNombre = new java.awt.Label();
        lblApellido = new java.awt.Label();
        lblId = new java.awt.Label();
        lblFechaNacimiento = new java.awt.Label();
        lblEmpresa = new java.awt.Label();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblGenero = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMOpConsultarConductor = new javax.swing.JMenuItem();
        jMOpMulta = new javax.swing.JMenuItem();
        jMOpAdminMapa = new javax.swing.JMenuItem();
        jMOpCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 153));
        setPreferredSize(new java.awt.Dimension(600, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Universidad del cauca ");
        jPanel2.add(jLabel3, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel8.setText("2020 | División de Tecnologías de la Información y las Comunicaciones Universidad del Cauca");
        jPanel4.add(jLabel8);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel3.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Apellido:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel3.add(jLabel2, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Identificacion:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel3.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Fecha nacimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel3.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Empresa:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        jPanel3.add(jLabel7, gridBagConstraints);

        lblNombre.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel3.add(lblNombre, gridBagConstraints);

        lblApellido.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel3.add(lblApellido, gridBagConstraints);

        lblId.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanel3.add(lblId, gridBagConstraints);

        lblFechaNacimiento.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        jPanel3.add(lblFechaNacimiento, gridBagConstraints);

        lblEmpresa.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        jPanel3.add(lblEmpresa, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Usuario:");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel4, new java.awt.GridBagConstraints());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Genero:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        jPanel3.add(jLabel9, gridBagConstraints);

        lblGenero.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        jPanel3.add(lblGenero, gridBagConstraints);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Opciones");

        jMOpConsultarConductor.setText("Consultar Conductor");
        jMOpConsultarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMOpConsultarConductorActionPerformed(evt);
            }
        });
        jMenu1.add(jMOpConsultarConductor);

        jMOpMulta.setText("Añadir multa");
        jMOpMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMOpMultaActionPerformed(evt);
            }
        });
        jMenu1.add(jMOpMulta);

        jMOpAdminMapa.setText("Mapa Entrada/Salida Vehiculos");
        jMOpAdminMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMOpAdminMapaActionPerformed(evt);
            }
        });
        jMenu1.add(jMOpAdminMapa);

        jMOpCerrarSesion.setText("Cerrar sesión");
        jMOpCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMOpCerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(jMOpCerrarSesion);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jMOpConsultarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMOpConsultarConductorActionPerformed
        VistaConsultaConductor vcc;
        vcc = new VistaConsultaConductor(this);
        vcc.setVisible(true);
    }//GEN-LAST:event_jMOpConsultarConductorActionPerformed

    private void jMOpAdminMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMOpAdminMapaActionPerformed
        GestorMapa gm = new GestorMapa();
        VistaMapa vm;
        vm = new VistaMapa();
        vm.setVisible(true);
        vm.actualizar(gm.actualizarMapa());
    }//GEN-LAST:event_jMOpAdminMapaActionPerformed

    private void jMOpCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMOpCerrarSesionActionPerformed
           this.setVisible(false);
           VistaLogin vl = new VistaLogin();
           vl.setVisible(true);
    }//GEN-LAST:event_jMOpCerrarSesionActionPerformed

    private void jMOpMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMOpMultaActionPerformed
         VistaRegistrarMulta vrm;
         vrm = new VistaRegistrarMulta();
         vrm.setVisible(true);
    }//GEN-LAST:event_jMOpMultaActionPerformed
    

    public void infoVigilante(String nombre,String apellido,String id,String fechaNacimiento,String genero,String empresa){
        lblNombre.setText(nombre);
        lblApellido.setText(apellido);
        lblId.setText(id);
        lblFechaNacimiento.setText(fechaNacimiento);
        lblGenero.setText(genero);
        lblEmpresa.setText(empresa);       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMOpAdminMapa;
    private javax.swing.JMenuItem jMOpCerrarSesion;
    private javax.swing.JMenuItem jMOpConsultarConductor;
    private javax.swing.JMenuItem jMOpMulta;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private java.awt.Label lblApellido;
    private java.awt.Label lblEmpresa;
    private java.awt.Label lblFechaNacimiento;
    private java.awt.Label lblGenero;
    private java.awt.Label lblId;
    private java.awt.Label lblNombre;
    // End of variables declaration//GEN-END:variables
}
