/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueaderotulcan.vista;

import parqueaderotulcan.controlador.GestorConductor;
import parqueaderotulcan.controlador.GestorMapa;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import parqueaderotulcan.modelo.Automovil;
import parqueaderotulcan.modelo.Conductor;

 /*
 * @author Felipe Vidal y Aldair Zemanate
 */

public class VistaConsultaConductor extends javax.swing.JFrame {
    VistaVigilante vistaPadreVigilante;
    /**
     * Creates new form VistaConsultarConductor
     */
    public VistaConsultaConductor(VistaVigilante vistaPadreVigilante) {
        initComponents();
        inicializarTabla();
        this.vistaPadreVigilante=vistaPadreVigilante;
        vistaPadreVigilante.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnGOpcion = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        rBSelectCodi = new javax.swing.JRadioButton();
        rBSelectId = new javax.swing.JRadioButton();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtIdentificacion = new java.awt.TextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblNombre = new java.awt.Label();
        lblApellido = new java.awt.Label();
        lblFechaNacimiento = new java.awt.Label();
        lblCedula = new java.awt.Label();
        lblGenero = new java.awt.Label();
        lblCodigo = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAutomovil = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        lblRol = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMOp = new javax.swing.JMenu();
        jMOpGestionMapa = new javax.swing.JMenuItem();
        jMORegistrarConductor = new javax.swing.JMenuItem();
        jMOpRegistrarAutomovil = new javax.swing.JMenuItem();
        jMOpVincularConductorAutomovil = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(700, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 100));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnGOpcion.add(rBSelectCodi);
        rBSelectCodi.setText("Código");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(rBSelectCodi, gridBagConstraints);

        btnGOpcion.add(rBSelectId);
        rBSelectId.setSelected(true);
        rBSelectId.setText("Documento de Identificación");
        rBSelectId.setRolloverEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(rBSelectId, gridBagConstraints);

        btnBuscar.setText("Buscar");
        btnBuscar.setMaximumSize(new java.awt.Dimension(90, 30));
        btnBuscar.setMinimumSize(new java.awt.Dimension(90, 30));
        btnBuscar.setPreferredSize(new java.awt.Dimension(90, 30));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(btnBuscar, gridBagConstraints);

        jLabel1.setText("Ingrese número del documento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jLabel1, gridBagConstraints);

        txtIdentificacion.setMinimumSize(new java.awt.Dimension(20, 60));
        txtIdentificacion.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel1.add(txtIdentificacion, new java.awt.GridBagConstraints());

        jLabel11.setText("Tipo de documento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(jLabel11, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Universidad del cauca ");
        jPanel2.add(jLabel3, new java.awt.GridBagConstraints());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Consultar conductor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jLabel4, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Información Conductor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jLabel2, gridBagConstraints);

        jLabel5.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel3.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Apellido:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel3.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Fecha nacimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        jPanel3.add(jLabel7, gridBagConstraints);

        jLabel8.setText("Cedula:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel3.add(jLabel8, gridBagConstraints);

        jLabel9.setText("Código:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        jPanel3.add(jLabel9, gridBagConstraints);

        jLabel10.setText("Genero:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel3.add(jLabel10, gridBagConstraints);

        lblNombre.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel3.add(lblNombre, gridBagConstraints);

        lblApellido.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel3.add(lblApellido, gridBagConstraints);

        lblFechaNacimiento.setPreferredSize(new java.awt.Dimension(70, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel3.add(lblFechaNacimiento, gridBagConstraints);

        lblCedula.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        jPanel3.add(lblCedula, gridBagConstraints);

        lblGenero.setMinimumSize(new java.awt.Dimension(30, 50));
        lblGenero.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanel3.add(lblGenero, gridBagConstraints);

        lblCodigo.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        jPanel3.add(lblCodigo, gridBagConstraints);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(200, 200));

        tblAutomovil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAutomovil.setMinimumSize(new java.awt.Dimension(300, 100));
        tblAutomovil.setPreferredSize(new java.awt.Dimension(600, 200));
        jScrollPane2.setViewportView(tblAutomovil);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        jPanel3.add(jScrollPane2, gridBagConstraints);

        jLabel13.setText("Rol:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        jPanel3.add(jLabel13, gridBagConstraints);

        lblRol.setMinimumSize(new java.awt.Dimension(30, 50));
        lblRol.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        jPanel3.add(lblRol, gridBagConstraints);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jMOp.setText("Opciones");

        jMOpGestionMapa.setText("Mapa Entrada/Salida Vehiculos");
        jMOpGestionMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMOpGestionMapaActionPerformed(evt);
            }
        });
        jMOp.add(jMOpGestionMapa);

        jMORegistrarConductor.setText("Registrar conductor");
        jMORegistrarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMORegistrarConductorActionPerformed(evt);
            }
        });
        jMOp.add(jMORegistrarConductor);

        jMOpRegistrarAutomovil.setText("Registrar automovil");
        jMOpRegistrarAutomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMOpRegistrarAutomovilActionPerformed(evt);
            }
        });
        jMOp.add(jMOpRegistrarAutomovil);

        jMOpVincularConductorAutomovil.setText("Vincular conductor-automovil");
        jMOpVincularConductorAutomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMOpVincularConductorAutomovilActionPerformed(evt);
            }
        });
        jMOp.add(jMOpVincularConductorAutomovil);

        jMenuBar1.add(jMOp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //Logica para buscar un conductor en la base de datos
        String id;
        Conductor conductor = null;
        GestorConductor consulConductor;
        id = txtIdentificacion.getText();
        if(id.equals("")){
            JOptionPane.showMessageDialog(null,"Debe ingresar el documento para continuar");
        }else{
            //Si se ha seleccionado el boton "Codigo" en la vista, se busca en la bases de datos por codigo
            if(rBSelectCodi.isSelected() == true ){
                consulConductor = new GestorConductor();
                //Se llama al respectivo metodo en la clase GestorConductor. El metodo se comunicacara con  los servicios del servidios para
                //buscar la informacion en la base de datos
                conductor=consulConductor.consultarConductorCodigo(id);
                 if(conductor!=null){
                    //Si existe el conductor, se busca en la base de datos los vehiculo asociados
                    Automovil [] newAutomovilesConsul=consulConductor.cosultarAutomovilCodigo(id);
                    mostrarConductor(conductor);
                    mostrarAutomovil(newAutomovilesConsul);
                }else{
                    JOptionPane.showMessageDialog(null,"El conductor con código "+id+" no existe en la bases de datos");
                    limpiarDatos();
                }
               
            }else{
                //Si se ha seleccionado el boton "Cedula" en la vista, se busca en la bases de datos por cedula
                consulConductor = new GestorConductor();
                //Se llama al respectivo metodo en la clase GestorConductor. El metodo se comunicacara con  los servicios del servidios para
                //buscar la informacion en la base de datos
                conductor=consulConductor.consultarConductorCedula(id);
                if(conductor.getCedula()!=null){
                    //Si existe el conductor, se busca en la base de datos los vehiculo asociados
                    Automovil [] newAutomovilesConsul=consulConductor.cosultarAutomovilCedula(id);
                    mostrarConductor(conductor);
                    mostrarAutomovil(newAutomovilesConsul);
                }else{
                    JOptionPane.showMessageDialog(null,"El conductor con cedula "+id+" no existe en la bases de datos");
                    limpiarDatos();
                }
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed
    
    private void jMORegistrarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMORegistrarConductorActionPerformed
        VistaRegistrarConductor vrg = new VistaRegistrarConductor(this);
        vrg.setVisible(true);
    }//GEN-LAST:event_jMORegistrarConductorActionPerformed

    private void jMOpRegistrarAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMOpRegistrarAutomovilActionPerformed
        VistaRegistrarAutomovil vra = new VistaRegistrarAutomovil(this);
        vra.setVisible(true);
    }//GEN-LAST:event_jMOpRegistrarAutomovilActionPerformed

    private void jMOpVincularConductorAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMOpVincularConductorAutomovilActionPerformed
        VistaVincularConductorAutomovil vvca = new VistaVincularConductorAutomovil(this);
        vvca.setVisible(true);
    }//GEN-LAST:event_jMOpVincularConductorAutomovilActionPerformed

    private void jMOpGestionMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMOpGestionMapaActionPerformed
        VistaMapa vm = new VistaMapa();
        GestorMapa gm = new GestorMapa();
        vm.actualizar(gm.actualizarMapa());
        
    }//GEN-LAST:event_jMOpGestionMapaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        vistaPadreVigilante.setVisible(true);
    }//GEN-LAST:event_formWindowClosed
    private void inicializarTabla(){
        tblAutomovil.setModel(new javax.swing.table.DefaultTableModel(new Object [] [] {},new String[]{"Placa","Marca","Tipo"}));
    } 
    public void limpiarDatos(){
        lblNombre.setText("");
        lblApellido.setText("");
        lblCedula.setText("");
        lblCodigo.setText("");
        lblFechaNacimiento.setText("");
        lblGenero.setText("");
        lblRol.setText("");
        inicializarTabla();
    }
    public void mostrarConductor(Conductor conductor){    
        lblNombre.setText(conductor.getNombre());
        lblApellido.setText(conductor.getApellido());
        lblCedula.setText(conductor.getCedula());
        lblCodigo.setText(conductor.getCodigo());
        lblFechaNacimiento.setText(conductor.getFecha_nacimiento());
        lblGenero.setText(conductor.getGenero());
        lblRol.setText(conductor.getRol());
    }
    public void mostrarAutomovil(Automovil[] automovil){
        inicializarTabla();
        DefaultTableModel model = (DefaultTableModel) tblAutomovil.getModel();
        Object rowData[] = new Object[7];
        for(Automovil auto: automovil){
            rowData[0] = auto.getPlaca();
            rowData[1] = auto.getMarca();
            rowData[2] = auto.getTipo();
            model.addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.ButtonGroup btnGOpcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMORegistrarConductor;
    private javax.swing.JMenu jMOp;
    private javax.swing.JMenuItem jMOpGestionMapa;
    private javax.swing.JMenuItem jMOpRegistrarAutomovil;
    private javax.swing.JMenuItem jMOpVincularConductorAutomovil;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private java.awt.Label lblApellido;
    private java.awt.Label lblCedula;
    private java.awt.Label lblCodigo;
    private java.awt.Label lblFechaNacimiento;
    private java.awt.Label lblGenero;
    private java.awt.Label lblNombre;
    private java.awt.Label lblRol;
    private javax.swing.JRadioButton rBSelectCodi;
    private javax.swing.JRadioButton rBSelectId;
    private javax.swing.JTable tblAutomovil;
    private java.awt.TextField txtIdentificacion;
    // End of variables declaration//GEN-END:variables
}
