/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueaderotulcan.vista;

import javax.swing.JOptionPane;
import parqueaderotulcan.controlador.GestorConductor;
import parqueaderotulcan.modelo.Conductor;

/**
 *
 * @author Felipe Vidal y Aldair Zemanate
 */
public class VistaRegistrarAutomovil extends javax.swing.JFrame {
    VistaConsultaConductor vcc;
    boolean estadoConductor;

    /**
     * Creates new form VistaRegistrarAutomovil
     */
    public VistaRegistrarAutomovil(VistaConsultaConductor vcc) {
        initComponents();
        this.vcc=vcc;
        vcc.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPlaca = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        txtMarca = new java.awt.TextField();
        jLabel5 = new javax.swing.JLabel();
        jComboTipoAutomovil = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtConductor = new java.awt.TextField();
        lblConductor = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Universidad del cauca ");
        jPanel2.add(jLabel3, new java.awt.GridBagConstraints());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Registrar automovil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jLabel4, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jLabel6.setText("2020 | División de Tecnologías de la Información y las Comunicaciones Universidad del Cauca");
        jPanel3.add(jLabel6);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Placa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtPlaca.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanel1.add(txtPlaca, new java.awt.GridBagConstraints());

        jLabel2.setText("Marca");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel1.add(jLabel2, gridBagConstraints);

        txtMarca.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel1.add(txtMarca, gridBagConstraints);

        jLabel5.setText("Tipo de automovil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel1.add(jLabel5, gridBagConstraints);

        jComboTipoAutomovil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOTO", "CARRO" }));
        jPanel1.add(jComboTipoAutomovil, new java.awt.GridBagConstraints());

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanel1.add(jButton1, gridBagConstraints);

        jLabel7.setText("Cedula conductor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jLabel7, gridBagConstraints);

        txtConductor.setPreferredSize(new java.awt.Dimension(60, 20));
        txtConductor.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txtConductorTextValueChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel1.add(txtConductor, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        jPanel1.add(lblConductor, gridBagConstraints);

        jLabel9.setText("Conductor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jLabel9, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GestorConductor gs = new GestorConductor();
        //Se comptueba que las casillas no se encuentren vacias
        if(txtPlaca.getText().equals("") || txtMarca.getText().equals("")||txtConductor.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Exiten campos vacios");

        }else{
            if(estadoConductor==true){
                gs.ingresarVehiculo(txtPlaca.getText(), txtMarca.getText(), jComboTipoAutomovil.getSelectedItem().toString(),txtConductor.getText());
            }else{
                JOptionPane.showMessageDialog(null,"El conductor no se encuentre registrado en la base de datos");
            }

        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        vcc.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void txtConductorTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txtConductorTextValueChanged
        GestorConductor gc = new GestorConductor();
        Conductor conductor;
        if (isNumeric(txtConductor.getText())==true){
            conductor = gc.consultarConductorCedula(txtConductor.getText());
                if(conductor.getCedula()!=null ){
                lblConductor.setText(conductor.getNombre()+" "+conductor.getApellido());
                estadoConductor=true;
            }
                else{  
                lblConductor.setText("");
                estadoConductor=false;
            }
        }
    }//GEN-LAST:event_txtConductorTextValueChanged
    private static boolean isNumeric(String cadena){
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException nfe){
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboTipoAutomovil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblConductor;
    private java.awt.TextField txtConductor;
    private java.awt.TextField txtMarca;
    private java.awt.TextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
