/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueaderotulcan.vista;

import java.util.Date;
import parqueaderotulcan.controlador.GestorVigilante;

/**
 *
 * @author Felipe Vidal y Aldair Zemanate
 */
public class VistaRegistrarVigilante extends javax.swing.JFrame {
    VistaAdministrador vistaPadreAdministrativo;
    /**
     * Creates new form VistaRegistrarVigilante
     */
    public VistaRegistrarVigilante( VistaAdministrador vistaPadreAdministrativo) {
        initComponents();
        this.vistaPadreAdministrativo=vistaPadreAdministrativo;
        vistaPadreAdministrativo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbNam = new javax.swing.JLabel();
        lblApeliidos = new javax.swing.JLabel();
        lblGen = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtName = new java.awt.TextField();
        lblEmpresa = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        txtId = new java.awt.TextField();
        txtEmpresa = new java.awt.TextField();
        btnGuardar = new javax.swing.JButton();
        jCBGenero = new javax.swing.JComboBox<>();
        lblFN1 = new javax.swing.JLabel();
        txtApe = new java.awt.TextField();
        lblUs = new java.awt.Label();
        txtUsuario = new java.awt.TextField();
        lblCon = new java.awt.Label();
        txtContra = new java.awt.TextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Universidad del cauca ");
        jPanel2.add(jLabel4, new java.awt.GridBagConstraints());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Registrar vigilante");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jLabel5, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 200));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lbNam.setText("Nombre:");
        jPanel1.add(lbNam, new java.awt.GridBagConstraints());

        lblApeliidos.setText("Apellidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel1.add(lblApeliidos, gridBagConstraints);

        lblGen.setText("Genero");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(lblGen, gridBagConstraints);

        lblId.setText("Identificación");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel1.add(lblId, gridBagConstraints);

        txtName.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(txtName, gridBagConstraints);

        lblEmpresa.setText("Empresa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(lblEmpresa, gridBagConstraints);

        jdcFecha.setMaxSelectableDate(new java.util.Date(253370786478000L));
        jdcFecha.setMinSelectableDate(new java.util.Date(-62135747922000L));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        jPanel1.add(jdcFecha, gridBagConstraints);

        txtId.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(txtId, gridBagConstraints);

        txtEmpresa.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(txtEmpresa, gridBagConstraints);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel1.add(btnGuardar, gridBagConstraints);

        jCBGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maculino", "Femenino", "Otro" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jCBGenero, gridBagConstraints);

        lblFN1.setText("Fecha Nacimiento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel1.add(lblFN1, gridBagConstraints);

        txtApe.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(txtApe, gridBagConstraints);

        lblUs.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel1.add(lblUs, gridBagConstraints);

        txtUsuario.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(txtUsuario, gridBagConstraints);

        lblCon.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanel1.add(lblCon, gridBagConstraints);

        txtContra.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(txtContra, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel8.setText("2020 | División de Tecnologías de la Información y las Comunicaciones Universidad del Cauca");
        jPanel4.add(jLabel8);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Logica para registrar capturar los datos y registrarlos en la base de datos
        GestorVigilante gv = new GestorVigilante();
        Date fechaNacimiento = jdcFecha.getDate();
        long d = fechaNacimiento.getTime();
        java.sql.Date fecha_nacimiento = new java.sql.Date(d);
        gv.RegistrarVigilante(txtId.getText(), txtName.getText(),txtApe.getText() ,fecha_nacimiento.toString(), jCBGenero.getSelectedItem().toString(), txtEmpresa.getText(), txtUsuario.getText(), txtContra.getText());
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        vistaPadreAdministrativo.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> jCBGenero;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JLabel lbNam;
    private javax.swing.JLabel lblApeliidos;
    private java.awt.Label lblCon;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblFN1;
    private javax.swing.JLabel lblGen;
    private javax.swing.JLabel lblId;
    private java.awt.Label lblUs;
    private java.awt.TextField txtApe;
    private java.awt.TextField txtContra;
    private java.awt.TextField txtEmpresa;
    private java.awt.TextField txtId;
    private java.awt.TextField txtName;
    private java.awt.TextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
